# The URL the site will be built for
base_url = "https://gaxxx.github.io"
title = "siwu's blog"
theme = "slim"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

default_language = "en"

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

taxonomies = [
    {name = "tags", paginate_by = 5, rss = true}
]

[languages.zh]
title = "siwu的博客"
build_search_index = false
taxonomies = [
    {name = "tags", paginate_by = 5, rss = true}
]

[extra]
slim_summary = true
slim_menu = [
    {url = "$BASE_URL/tags", name = "Tags"}
]
# Links to show at the bottom of the menu
slim_social = [
    {url = "https://www.linkedin.com/in/gaxxx", name = "LinkedIn"},
    {url = "https://github.com/gaxxx", name = "Github"}
]
